#!/bin/bash
# Run after dropping new photos into assets/images/food/.
# Converts HEIC -> JPG (browsers other than Safari can't show HEIC), caps size at
# 1600px, and rewrites assets/js/food.js, the list the Cooking grid is built from.
cd "$(dirname "$0")/assets/images/food" || exit 1

for f in *.[Hh][Ee][Ii][Cc]; do
  [ -e "$f" ] || continue
  out="${f%.*}.jpg"
  [ -e "$out" ] || sips -s format jpeg -s formatOptions 82 -Z 1600 "$f" --out "$out" >/dev/null
done

{
  echo "// Generated by update-food.sh - do not edit by hand."
  echo "const FOOD_IMAGES = ["
  for f in *.jpg *.jpeg *.png *.webp *.JPG *.JPEG *.PNG; do
    [ -e "$f" ] && echo "  \"/assets/images/food/$f\","
  done | sort -u
  echo "];"
} > ../../js/food.js
echo "Wrote $(grep -c '"/assets' ../../js/food.js) images to assets/js/food.js"
