// Sample postings for the portfolio demo. Same shape as the rows returned by
// match_umass_jobs() in the real app, but written by hand — not scraped data.
const SAMPLE_JOBS = [
  {
    title: "IT Help Desk Consultant",
    department: "Information Technology",
    description: "Answer walk-in, phone and chat questions from students and staff. Troubleshoot Wi-Fi, email, account and software problems on Windows and macOS, and escalate hardware issues to technicians.",
    skills: ["Troubleshooting", "Customer Service", "Windows", "macOS"],
    is_work_study: false, on_campus: true, pay_min: 16.5, pay_max: 18, hours_per_week: "10-15", hiring_period: "Academic Year",
  },
  {
    title: "Student Web Developer",
    department: "College of Information & Computer Sciences",
    description: "Build and maintain department web pages and small internal tools. Work with HTML, CSS, JavaScript and Python, fix accessibility issues, and review pull requests with the web team.",
    skills: ["JavaScript", "Python", "HTML/CSS", "Git"],
    is_work_study: false, on_campus: true, pay_min: 18, pay_max: 22, hours_per_week: "10-20", hiring_period: "Academic Year",
  },
  {
    title: "Undergraduate Research Assistant – Machine Learning Lab",
    department: "Manning College of Information & Computer Sciences",
    description: "Support graduate researchers by cleaning datasets, running experiments and writing Python scripts for data analysis. Some familiarity with NumPy, pandas or PyTorch is helpful. Linear algebra and statistics coursework preferred.",
    skills: ["Python", "Data Analysis", "Machine Learning", "Linear Algebra"],
    is_work_study: false, on_campus: true, pay_min: 17, pay_max: 20, hours_per_week: "8-12", hiring_period: "Academic Year",
  },
  {
    title: "Math Tutor",
    department: "Learning Resource Center",
    description: "Tutor students one-on-one and in drop-in sessions for calculus, linear algebra and introductory statistics. Help students build study habits and explain problem-solving strategies clearly.",
    skills: ["Tutoring", "Calculus", "Linear Algebra", "Communication"],
    is_work_study: false, on_campus: true, pay_min: 16, pay_max: 17, hours_per_week: "6-12", hiring_period: "Academic Year",
  },
  {
    title: "CS Course Grader",
    department: "Manning College of Information & Computer Sciences",
    description: "Grade programming assignments in Java and Python for an introductory computer science course, hold weekly office hours, and give written feedback on code style and correctness.",
    skills: ["Java", "Python", "Teaching", "Attention to Detail"],
    is_work_study: false, on_campus: true, pay_min: 17, pay_max: 17, hours_per_week: "8-10", hiring_period: "Fall Semester",
  },
  {
    title: "Data Entry Assistant",
    department: "Office of the Registrar",
    description: "Enter and verify student records, scan documents, and keep spreadsheets organized in Excel. Accuracy and confidentiality are essential.",
    skills: ["Data Entry", "Excel", "Organization", "Confidentiality"],
    is_work_study: true, on_campus: true, pay_min: 15, pay_max: 15.5, hours_per_week: "10-15", hiring_period: "Academic Year",
  },
  {
    title: "Dining Commons Cashier",
    department: "UMass Dining",
    description: "Greet guests, process meal swipes and card payments at the register, and keep food stations stocked and clean during busy meal periods.",
    skills: ["Customer Service", "Cash Handling", "Teamwork"],
    is_work_study: false, on_campus: true, pay_min: 15.75, pay_max: 16.5, hours_per_week: "8-20", hiring_period: "Academic Year",
  },
  {
    title: "Line Cook – Franklin Dining Commons",
    department: "UMass Dining",
    description: "Prepare and cook menu items following recipes and food safety standards. Work in a fast-paced kitchen alongside professional chefs. No experience required; training provided.",
    skills: ["Cooking", "Food Safety", "Teamwork"],
    is_work_study: false, on_campus: true, pay_min: 16, pay_max: 17.5, hours_per_week: "10-20", hiring_period: "Academic Year",
  },
  {
    title: "Barista – Campus Center Café",
    department: "Auxiliary Enterprises",
    description: "Make espresso drinks and serve customers in a busy café, handle the register, and help open or close the shop.",
    skills: ["Customer Service", "Cash Handling", "Food Service"],
    is_work_study: true, on_campus: true, pay_min: 15.5, pay_max: 16, hours_per_week: "6-15", hiring_period: "Academic Year",
  },
  {
    title: "Social Media Assistant",
    department: "University Relations",
    description: "Create Instagram and TikTok content, design graphics in Canva, write captions, and schedule weekly posts. Photography and video editing experience is a plus.",
    skills: ["Social Media", "Graphic Design", "Writing", "Video Editing"],
    is_work_study: false, on_campus: true, pay_min: 16, pay_max: 18, hours_per_week: "8-12", hiring_period: "Academic Year",
  },
  {
    title: "Graphic Design Intern",
    department: "Student Engagement & Leadership Center",
    description: "Design flyers, posters and digital signage for student events using Adobe Illustrator and Photoshop. Build a portfolio while working with student organizations.",
    skills: ["Graphic Design", "Adobe Illustrator", "Photoshop", "Marketing"],
    is_work_study: true, on_campus: true, pay_min: 16, pay_max: 17, hours_per_week: "8-12", hiring_period: "Academic Year",
  },
  {
    title: "Lifeguard",
    department: "Campus Recreation",
    description: "Supervise swimmers at the Recreation Center pool, enforce safety rules and respond to emergencies. Current lifeguard, CPR and First Aid certification required.",
    skills: ["Lifeguarding", "CPR", "First Aid", "Safety"],
    is_work_study: false, on_campus: true, pay_min: 17, pay_max: 19, hours_per_week: "6-15", hiring_period: "Academic Year",
  },
  {
    title: "Intramural Sports Official",
    department: "Campus Recreation",
    description: "Referee intramural basketball, soccer, volleyball and squash games. Enforce rules fairly, manage game time and communicate with team captains. Training provided; athletic experience preferred.",
    skills: ["Sports", "Leadership", "Conflict Resolution", "Communication"],
    is_work_study: false, on_campus: true, pay_min: 15.5, pay_max: 16.5, hours_per_week: "5-12", hiring_period: "Academic Year",
  },
  {
    title: "Fitness Center Attendant",
    department: "Campus Recreation",
    description: "Check in members at the front desk, monitor the weight room and cardio floor, clean equipment and help new members use machines safely.",
    skills: ["Customer Service", "Fitness", "Safety"],
    is_work_study: true, on_campus: true, pay_min: 15, pay_max: 15.5, hours_per_week: "6-12", hiring_period: "Academic Year",
  },
  {
    title: "Library Circulation Assistant",
    department: "W.E.B. Du Bois Library",
    description: "Check books in and out, shelve materials, and help patrons find resources at the circulation desk. Quiet, detail-oriented work with flexible evening shifts.",
    skills: ["Customer Service", "Organization", "Attention to Detail"],
    is_work_study: true, on_campus: true, pay_min: 15, pay_max: 15, hours_per_week: "8-15", hiring_period: "Academic Year",
  },
  {
    title: "Front Desk Receptionist",
    department: "Residential Life",
    description: "Staff the residence hall front desk: answer phones, sort mail and packages, issue temporary keys and assist residents with questions.",
    skills: ["Customer Service", "Office Administration", "Communication"],
    is_work_study: true, on_campus: true, pay_min: 15, pay_max: 15.5, hours_per_week: "8-12", hiring_period: "Academic Year",
  },
  {
    title: "Chemistry Lab Assistant",
    department: "Chemistry",
    description: "Prepare solutions, wash glassware, sort chemical inventory and keep safety logs for teaching labs. Must complete lab safety training.",
    skills: ["Lab Safety", "Chemistry", "Organization"],
    is_work_study: true, on_campus: true, pay_min: 15.5, pay_max: 16, hours_per_week: "8-12", hiring_period: "Academic Year",
  },
  {
    title: "Grounds Crew Worker",
    department: "Physical Plant",
    description: "Mow, rake, plant and maintain campus gardens and landscaping. Outdoor physical work; early morning shifts available.",
    skills: ["Landscaping", "Physical Work", "Teamwork"],
    is_work_study: false, on_campus: true, pay_min: 16, pay_max: 17, hours_per_week: "10-20", hiring_period: "Summer",
  },
  {
    title: "After-School Program Counselor",
    department: "Amherst Community Center",
    description: "Lead homework help, games and arts activities for elementary school children in an off-campus after-school program. Experience working with children preferred.",
    skills: ["Childcare", "Tutoring", "Leadership"],
    is_work_study: true, on_campus: false, pay_min: 16, pay_max: 17, hours_per_week: "10-15", hiring_period: "Academic Year",
  },
  {
    title: "Retail Sales Associate",
    department: "Amherst Outdoor Outfitters",
    description: "Help customers pick out gear, run the register and restock the sales floor at a downtown Amherst store. Friendly and outgoing personality needed.",
    skills: ["Sales", "Customer Service", "Cash Handling"],
    is_work_study: false, on_campus: false, pay_min: 15, pay_max: 16, hours_per_week: "10-20", hiring_period: "Academic Year",
  },
  {
    title: "Software Support Intern",
    department: "Pioneer Valley Tech Solutions",
    description: "Off-campus internship helping a small local company test software, write documentation and troubleshoot customer issues. Basic programming in Python or Java required.",
    skills: ["Python", "Java", "Troubleshooting", "Documentation"],
    is_work_study: false, on_campus: false, pay_min: 20, pay_max: 25, hours_per_week: "10-15", hiring_period: "Academic Year",
  },
  {
    title: "Box Office Assistant",
    department: "Fine Arts Center",
    description: "Sell tickets for concerts and performances, answer patron questions by phone and email, and help usher at events.",
    skills: ["Customer Service", "Cash Handling", "Events"],
    is_work_study: true, on_campus: true, pay_min: 15, pay_max: 15.5, hours_per_week: "6-12", hiring_period: "Academic Year",
  },
  {
    title: "Event Setup Crew",
    department: "Campus Center Events",
    description: "Set up and break down tables, chairs, staging and audio-visual equipment for conferences and student events. Lifting required.",
    skills: ["Events", "Physical Work", "Audio/Visual"],
    is_work_study: false, on_campus: true, pay_min: 15.5, pay_max: 16.5, hours_per_week: "5-15", hiring_period: "Academic Year",
  },
  {
    title: "Peer Writing Tutor",
    department: "Writing Center",
    description: "Help students brainstorm, organize and revise essays and lab reports in one-on-one sessions. Strong writing skills and patience required.",
    skills: ["Writing", "Tutoring", "Communication", "Editing"],
    is_work_study: false, on_campus: true, pay_min: 16, pay_max: 17, hours_per_week: "6-10", hiring_period: "Academic Year",
  },
];
